language: cpp
matrix:
  include:
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-8
        - g++-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  - os: osx
    osx_image: xcode10.1

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:webkit-team/ppa -y; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -q; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
- wget -c -nv "https://d30pueezughrda.cloudfront.net/juce/juce-5.4.3-$TRAVIS_OS_NAME.zip"
- unzip ./juce-5.4.3-$TRAVIS_OS_NAME.zip -d $HOME

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -y install libasound2-dev libjack-jackd2-dev libxinerama-dev libgl1-mesa-dev libgtk-3-dev libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev; fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then gcc --version; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd "./Builds/LinuxMakefile"; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then make -j$(nproc) CONFIG=Release; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then cd "./Builds/MacOSX"; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then xcodebuild -project sfizz.xcodeproj -alltargets -configuration Release build; fi
- cd ./../../

after_success:
- export VERSION=$(git describe --tags)
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DEPLOYFILE=sfizz-$VERSION-x86_64.AppImage; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget -c -nv "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then chmod +x linuxdeploy-x86_64.AppImage; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then for size in 16 32 48 128 256; do dirname="Sfizz/usr/share/icons/hicolor/${size}x${size}/apps"; mkdir -p $dirname; cp ./resources/icons/icon_${size}px.png ./${dirname}/sfizz.png; done; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./linuxdeploy-x86_64.AppImage --appdir=Sfizz --desktop-file=./resources/linux/sfizz.desktop --executable=./Builds/LinuxMakefile/build/sfizz --output=appimage; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then export DEPLOYFILE=sfizz-$VERSION.dmg; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then mkdir ./output; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then cp -r ./Builds/MacOSX/build/Release/* ./output/; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then cp ./resources/icons/icon.icns ./output/sfizz.app/Contents/Resources/; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then hdiutil create /tmp/tmp.dmg -ov -volname "sfizz-$VERSION" -fs HFS+ -srcfolder "./output/"; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then hdiutil convert /tmp/tmp.dmg -format UDZO -o ./$DEPLOYFILE; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: cc6IkdalZRb+lOWzPkubCUvTcP9lBwiNBBPkXWVmeX7YXkdQlsoVQ11bZThd1Go+5Lt+jGFtEqEjJ0L7GxpdatEeBMEK5HXl0QtHAybl9J4Ax7hKba8FSX5RqPFOuKixCob6eCqJRchT26qRsQE/WYMY8DmproEFGMBHk0K4HXDWEq0HP8dbWVx3KudvellCYszUrVQYb2s49sDiF8OwSog5TiqdBqO5PRcqyt2ySmHgqwBYq7XV0pb+DxcKJcc7/gCBpBN7nyEhl8gmKELypLF81l8xUDBUjRy1jjf0r33ISHpX1MWeWIN9YzSNL0aLPQvwynAQ7OeckFAIMABah2UuYcxdd4ioXduPTbprVYpSwIyyxkeafK2jxgxwoKWi9GJZ3yAUHNS/V7Gh5DsFb7C6QDqr5gOxOMtjHwjmHnxmD44SsugjSosVzirvQR+JbrSsPsmZThQjCvwG+7hO3JatX4BXA7bp9WtgsoMrCH61gCp2GogQVLvYpgRpVErKK8PMTkt71OouewTDqD5iwc3N/2pNWP3cXxpPegerjl4R2sY0sZ57WRfW8ts7akPyqJZa2uKpzpM0eXy35fZl6WoJSlIv3akCnzdtLtaWAptzfXhgRSlF/33+gZ3jRcSP7ca2YpUviuZ+KYk+uGfMh092CMRMjPv1Et5h7zYGD+o=
  file: "$DEPLOYFILE"
  on:
    repo: sfztools/sfizz
    tags: true
